name: Deploy Vue App

on:
  push:
    branches:
      - main  # 主分支名可能因仓库而异

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Stop and remove any existing container
          docker stop admin-interface || true
          docker rm admin-interface || true
          # Remove any existing image
          docker rmi admin-interface || true
          # Build the Docker image on the server
          docker build -t admin-interface .
          # Run the new container
          docker run -d --name admin-interface -p 80:80 admin-interface
