name: Deploy Admin Interface

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t admin-interface .
        docker save admin-interface -o ./admin-interface.tar
        chmod 644 ./admin-interface.tar

    - name: Upload the Docker image to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./admin-interface.tar"
        target: "~/admin-interface.tar"

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker stop admin-interface
          docker rm admin-interface
          docker rmi admin-interface || true
          docker load -i ~/admin-interface.tar/admin-interface.tar
          docker run -d --name admin-interface -p 80:80 admin-interface
          rm -rf ~/admin-interface.tar
          